name: Resonates
favicon: null
layout_spectrum: 0.5249561131931841
typography_spectrum: 0.0332614341750741
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6221281012985855
  lightness: 0.7622251391876489
  saturation: 0.039037511916831136
  rhythmicContrast: 0.9563593724742532
purpose: []
