analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.222973
  lightness: 0.788288
  rhythmicContrast: 0.490991
  saturation: 0.197072
cta: {}
layout_spectrum: 0.438063
name: Resonates
opengraph: {}
purpose: []
typography_spectrum: 0.288288
